### ISSUE TITLE
Is it possible to get the good image back?

### ISSUE THREAD

**Issue by acgc99** [nagolinc/ComfyUI_FastVAEDecorder_SDXL#4]
This node is saving so much time to test prompts and seeds (slow decode in my low VRAM laptop). I wonder if there is an option to load the low quality image back into ComfyUI and do the SD XL usual VAE, just to avoid running the KSampler again. I would do this only with images I liked.

**Comment by nagolinc** [comment]
If you use "fixed" seed, comfyui will only re-run the parts of the ui that have changed

So, for example:
* choose seed
* generate -> view with fast vae
* attach actual vae
* generate again (this should only run the vae node)

![image](https://github.com/user-attachments/assets/1f7b8092-5ec5-4395-b719-dc78d08068df)

**Comment by acgc99** [comment]
I know I can do that and I used it sometimes, but it is not what I am looking for. When I have a complex prompt, many images have bad anatomy and I want to avoid decoding them since it takes ~1 minute for an image I don't want. My idea is to use the quick decoder to get an idea of image composition and find potential candidates. Therefore, seed is not fixed. I was looking for something to load and encode the image again to finally decode it normally, just to avoid running the KSampler again.

**Comment by nagolinc** [comment]
I'm not really sure what you're asking for.  It seems like you could:
* start with seed=0 and latent attached to fastlatenttoimage
* render
* if it looks bad, manually increment the seed and try again
* when you find the seed you want, attach latent to vae decode

https://github.com/user-attachments/assets/c268b6e6-4444-4ac0-9513-0ce699c742bf


Is there some other way you imagined it working?

**Comment by acgc99** [comment]
Thanks for your answers, however, that's still not what I want exactly. Currently I'm saving the fast decoded images and after selecting the right ones, I have to load them in comfyui, run the full workflow but using the usual vae decode to get the final images. I'd like to skip running the full workflow. In other words, I'd like to load this image:
![256654197-4fc7bd01-81ac-439a-b71c-909e99475971](https://github.com/user-attachments/assets/79c3158e-83f4-4e73-962c-bdd972bc51d3)
And get:
![256654211-34b060c5-6a8d-45dd-a83e-ff4b521fb057](https://github.com/user-attachments/assets/2a7e3600-6763-487f-8a35-9975dc577b37)
regardless of how the image was generated.

Something like:
![Screenshot 2024-08-07 170753](https://github.com/user-attachments/assets/d11f10d9-a49e-4c22-b8f7-c25862566824)

**Comment by nagolinc** [comment]
that's mathematically  not possible because latents => image is a lossy transformation (the matrix is not invertible).

To do this you would have to:
* save the latents corresponding to each image separately (using https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Experimental/SaveLatent/)
* reload those latents and run through VAE

**Comment by acgc99** [comment]
Understood, thanks!
